### ISSUE TITLE
Can't Working on my LS-420D

### ISSUE THREAD

**Issue by ozdroid** [rogers0/OpenLinkstation#2]
hello.my device is LS-420D ( 1.80 fireware),i follow your tutorial , but after Step1 reboot, it's not working...could you tell me how i config the " lib/config " in LS-420.thx

**Comment by rogers0** [comment]
Could you please provide more info? Which part is not working?
lib/config default should be working OK. It's for "just in case" you want to change default password, etc.

I guess you just didn't get the newly DHCPed IP address of that box. Please try nmap on Linux, or Fing app on an iOS device. (surely you need to connect them in the same network)

**Comment by rogers0** [comment]
Please also notice the status line in the README.md:
LS-420 1.80 ~ 1.81 (Debian Wheezy-backport / Buffalo kernel) (upgrade to Jessie is OK, but direct bootstrap to Jessie still has issue)

So currently it's recommend to choose "wheezy" when working on LS-420 box.

**Comment by ozdroid** [comment]
thanks for your answer，i solved the problem by change router gateway to 192.168.11.1  
B.T.W, will u  add own compile kernel for linkstation-ls420 in the future update. there is a page about that: https://tohenk.wordpress.com/2014/12/11/compiling-debian-wheezy-kernel-for-linkstation-ls421de/

**Comment by rogers0** [comment]
Thanks for your feedback!

Oh, it's your blog :-)
I happened to visit your blog and already tried your DTS and scripts to build kernel, however it's not working on my LS420D box. (maybe because yours is LS421DE?)
And I did check the root cause by dmesg dumping to filesystem while initramfs booting. I found the system can boot, but the network (eth0 or eth1) cannot be enabled correctly. So ssh to the box always fails.

> i solved the problem by change router gateway to 192.168.11.1

Could you provide more info, please? Because I did find issue on Jessie, but it turn out to be OK when I do it in Wheezy. I don't have time yet to dig out the reason.
Thank you!

**Comment by ozdroid** [comment]
sorry ,it‘s not my page....

**Comment by ststay** [comment]
Hi my name is Stefan...
I have a LS420D32D and followed your suggestions...
Configured wheezy with bootstrap, use-buffalo-kernel and system-md=1
All was fine, except /mnt/array1/rootfs/proc didn't get unmounted...

So i did this manually and deleted /mnt/array1/rootfs

Tested your script 2 times, but with the result of Error-Code E07 on the LS...

So my question for quick steppin in is (in short)... "What is done with the uImage.buffalo kernel, when running your script?"  I thought, the root-partition is changed in the image, so that /mnt/array1/ is used for root-partition and the newly created initrd holds the modules for accessing the raid devices...
What went wrong???

Sorry for my question, i'd spending so much time recovering the brick station 2 times...
