### ISSUE TITLE
LS-QVL device tree

### ISSUE THREAD

**Issue by slumpz** [rogers0/OpenLinkstation#3]
Can you please by chance create the dev tree (and maybe the whole patch) for LS-QVL, or at least give me some hints? Right now I don't understand the ocp@ and gpio part.

Thank you very much.

**Comment by rogers0** [comment]
I'm sorry I don't have the device, so it's hard for me to do the real work.
However, here's some ideas if I have chance to continue my work on new device:
- Main idea: I guess QVL is the same series as VL (1-bay) and WVL (2-bay), so probably the current VL/WVL DTS might just work (to say, boot), if removing 3 HDD and only have 1 HDD.
- Here's how:
  0. backup ALL data. I will NOT be responsible for any of data loss
  1. leave only 1st HDD, remove other 3 HDDs
  2. do a buffalo recovery (firmware can be download from: http://buffalo.jp/download/driver/hd/ls_fw.html or http://buffalo.jp/download/driver/hd/ls_fw-mac.html )
  3. run "get-ssh" to get ssh in
  4. change the InitVal() in lib/shell_lib, to let the script adapt to the new device.
  5. run "1_debootstrap/build_rootfs_with_buffalo-kernel.sh", after that restart the device
  6. pray the box to boot. you can use netconsole to see the boot log even before ssh daemon start. just by command on the PC in the same network: `ip a add 192.168.11.1/24 dev eth0; nc -l -u -p 6666 | tee ~/netconsole.log`
  7. if boot OK, congrats! the rest of work is much easier, which to support the rest of 3 HDDs. if not, please send me the ~/netconsole.log file, and let's debug.

**Comment by slumpz** [comment]
Thank you very much for your quick response.

Actually I had my box up and running Debian for a while now, however it is using buffalo kernel.

My goal is to build new kernel because I'm in need of using the tun/tap device, so I would like to know how to make dts/dtb for the box.

I have read your patch here https://github.com/rogers0/patchset/blob/master/linkstation/dts_wxl-wsxl-wvl-vl/0002-ARM-dts-add-buffalo-linkstation-ls-wvl-vl.patch but couldn't understand the part with pin control and gpio values.

So if you can give me some infos about that, that would be very great.

Thanks again.

**Comment by rogers0** [comment]
Understand your situation.

For the pin value and gpio value, I have to admit only having limited knowledge.
But it's quite related to the HW, to be specific, chipset, which should be defined in devel manual of the SoC.

I created the DTS by referring other kirkwood based device's DTS, and various patchset on various forum/BBS, merge them and try different combinations. The final result works perfectly on my boxes, but it was a hard work.

I still suggest you to try the ideas in previous post. Since you're already on a Debian system, you can simply install Jessie kernel + VL/WVL DTB. You can read "1_debootstrap/build_rootfs_with_buffalo-kernel.sh" and "lib/shell_lib" for clue.
A more detailed instruction is upon request.

Actually, I think if you ONLY need tun/tap kernel module, you can simply compile it by using buffalo's kernel source. (http://opensource.buffalo.jp/ls-x-165.html)
BTW. I use Debian because I rely on it's security updates (including kernel).

Good luck!

**Comment by slumpz** [comment]
Thanks much for your help. I really appreciate it. I hope I'll get good result with your clues.

Since this is not an issue, I will close this thread.
