### ISSUE TITLE
LS-WXL step 2?

### ISSUE THREAD

**Issue by cthog** [rogers0/OpenLinkstation#4]
Hi there.  Sorry to be a noob, I really tried to figure this out on my own, but can't seem to get it.

I'm running an LS-WXL, where I've pulled one hard drive, so I've just one in there now.  (I tried your steps with the 2 in, and got an E06, so I've just recovered from that.)

I've successfully performed Step 1, but on step 2, I'm not sure what to do with mount /dev/<root dev> /mnt

Unless I'm mistaken, we're supposed to substitute something in for <root dev>, but I can't figure out what it is.  I thought it might be /dev/md1, but when I try step 2, I get "cannot find rootfs tarball", which tends to make me think I've got it wrong.  Can you give me some pointers on how to get this thing installed?

Really appreciate your work on this script--I managed to get debian on this thing the long way a few years ago, but have since forgotten everything, so I thought this was a godsend.

**Comment by cthog** [comment]
Just as an update, tried using the command mount /dev/$root /mnt.  Same problem with not finding rootfs tarball.  What am I missing?

**Comment by hiroTM** [comment]
Hello cthog.
"/dev/$root" rather than, I think that it is "/dev/sda2" or "/dev/md2" may be mount.
You might've already resolved.

**Comment by rogers0** [comment]
Sorry for the late reply.
I have to admit that I'm not always testing step-2, because after step-1 the running Debian is already built. After that you can move the rootfs to anywhere you like. The step-2 script is only an example how to do it in quick way.

the tarball is created in script step-1:
```
ChrootEnd $TARGET
[ $RET -gt 0 ] && exit 0
cd $TARGET
echo tar cf ../rootfs.tar .
tar cf ../rootfs.tar .
```

So if the tarball is missing in your environment, I guess you got something wrong with `ChrootEnd $TARGET` command.
If you can figure out what was wrong with that, maybe you can send me a pull request. :-)

**Comment by rogers0** [comment]
I just fixed the issue, caused by read-only mount of /boot.
Please try the latest version from master branch. Sorry about the trouble and thank you for your patience!
